attempt at fixing Windows cache clearer problem by removing loaded ma…
nens/threedi-results-analysis pull request #153
Opened 2017-07-04 14:35 UTC by jackieleng

…players

2017-07-04 14:41 UTC, jackieleng commented
![](https://github.trello.services/images/mini-trello-icon.png) [[qgis plugin] cache flush can't remove cache file [1]](https://trello.com/c/pd5uJG74/1907-qgis-plugin-cache-flush-cant-remove-cache-file-1)

2017-07-06 12:47 UTC, jsmits requested changes
Ook graag een regel aan de CHANGES toevoegen.

2017-07-06 12:47 UTC, jsmits commented on stats/utils.py
> +from qgis.core import (
Beter imports op losse regels. Dan doen we het allemaal (Lars, jij en ik) op dezelfde manier.

2017-07-06 13:26 UTC, jsmits commented on stats/utils.py
> +from qgis.core import (
Heb hier Trello taken voor gemaakt:  ``isort -sl **/*.py`` over alle (threedi) repo's en vervolgens isort laten uitvoeren door Jenkins bij testen van nieuwe PR's.

2017-07-06 13:27 UTC, merged